version: "3.8"

services:
  producao_qualidade:
    image: nginx:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
      - traefik_public
        #ports:
        #- "3000:80"
        #- "3000:443"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.routers.producao_qualidade.rule=Host(`producao-qualidade.usekingjoe.com.br`)"
        - "traefik.http.routers.producao_qualidade.entrypoints=websecure"
        - "traefik.http.routers.producao_qualidade.priority=1"
        - "traefik.http.routers.producao_qualidade.tls.certresolver=le"
        - "traefik.http.routers.producao_qualidade.service=producao_qualidade"
        - "traefik.http.services.producao_qualidade.loadbalancer.server.port=80"

networks:
  traefik_public:
    external: true
    attachable: true
  agent_network:
    external: true

