version: "3.8"

services:
  nginx:
    image: nginx:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
      - traefik_public
        #ports:
        #- "3000:80"
        #- "3000:443"
    deploy:
      mode: replicated
      replicas: 4
      placement:
        constraints: [ node.role == manager ]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.routers.nginx.rule=Host(`api_portal_cliente.universiflat.com.br`)"
        - "traefik.http.routers.nginx.entrypoints=websecure"
        - "traefik.http.routers.nginx.priority=1"
        - "traefik.http.routers.nginx.tls.certresolver=le"
        - "traefik.http.routers.nginx.service=nginx"
        - "traefik.http.services.nginx.loadbalancer.server.port=80"

networks:
  traefik_public:
    external: true
    attachable: true
  agent_network:
    external: true
